[package]
name = "lutra-bin-python"
version = "0.1.0"
edition = "2021"

[lib]
name = "lutra_bin"
crate-type = ["cdylib"]
test = false

[dependencies]
lutra-bin = { version = "0.1.0", path = "..", default-features = false, features = [
    "std",
] }
postgres = "0.19.10"
pyo3 = "0.22.0"
