[package]
name = "lutra-bin-python"
version = "0.1.0"
edition = "2021"

[lib]
name = "lutra_bin"
crate-type = ["cdylib"]
test = false

[dependencies]
lutra-bin = { workspace = true, features = ["std"] }
pyo3 = "0.25.0"
