[package]
name = "lutra-cli"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "lutra"
path = "src/cli.rs"
bench = false
test = false

[dependencies]
lutra-bin = { path = "../lutra-bin" }
lutra-compiler = { path = "../lutra-compiler", features = ["clap"] }
lutra-ir = { path = "../lutra-ir" }
lutra-runtime = { path = "../lutra-runtime" }

log = { workspace = true }
clap = { version = "4.4.18", features = ["derive"] }
env_logger = { workspace = true }
anyhow = { workspace = true }
