[package]
name = "lutra-cli"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "lutra"
path = "src/cli.rs"
bench = false
test = false

[dependencies]
lutra-bin = { path = "../lutra-bin" }
lutra-compiler = { path = "../lutra-compiler", features = ["clap"] }
lutra-runtime = { path = "../lutra-runtime" }

tracing = { workspace = true }
clap = { version = "4.4.18", features = ["derive"] }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
lutra-db-driver = { version = "0.1.0", path = "../lutra-db-driver" }
tokio-postgres = "0.7.13"
tokio = { version = "1.43.0", features = ["rt", "macros"] }
