[workspace]
members = [
    "tests",
    "lutra-bin",
    "lutra-codegen",
    "lutra-input-tui",
    "lutra-runtime",
    "lutra-typed-data",
    "lutra-frontend",
    "lutra-ir",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT or Apache 2.0"
repository = "https://code.murerzen.eu/lutra-data"
rust-version = "1.82"
version = "0.1.0"

[workspace.dependencies]
itertools = "0.13.0"
log = "0.4.22"
thiserror = "1.0.65"
anyhow = "1"
chumsky = "0.9.2"
env_logger = "0.11.5"
insta = "1.40.0"
