[package]
name = "lutra-data"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
lutra-parser = { path = "lutra-parser" }
lutra-bin = { path = "lutra-bin" }

[build-dependencies]
lutra-codegen = { path = "./lutra-codegen" }

[workspace]
members = ["lutra-bin", "lutra-codegen", "lutra-parser"]

[workspace.package]
edition = "2021"
license = "MIT or Apache 2.0"
repository = "https://code.murerzen.eu/lutra-data"
rust-version = "1.82"
version = "0.1.0"
