[workspace]
members = [
    "example",
    "lutra-bin",
    "lutra-codegen",
    "lutra-input-tui", "lutra-lang",
    "lutra-parser",
    "lutra-typed-data",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT or Apache 2.0"
repository = "https://code.murerzen.eu/lutra-data"
rust-version = "1.82"
version = "0.1.0"
