[package]
name = "lutra-typed-data"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
lutra-bin = { workspace = true }

[build-dependencies]
lutra-codegen = { workspace = true }
