[package]
name = "lutra-runtime"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
lutra-bin = { path = "../lutra-bin" }
lutra-frontend = { path = "../lutra-frontend" }

# for the IR parser
chumsky = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }

[dev-dependencies]
insta = { workspace = true }

[build-dependencies]
lutra-codegen = { path = "../lutra-codegen" }
