[package]
name = "lutra-codegen"

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true


[dependencies]
bytes = "1"
lutra-frontend = { path = "../lutra-frontend" }
lutra-bin = { path = "../lutra-bin" }
