[registry]
default = "codeberg-org"

[registries.codeberg-org]
index = "sparse+https://codeberg.org/api/packages/lutra/cargo/"

[target.'cfg(target_os = "linux")']
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]
