[package]
name = "lutra-tui"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true }
itertools = { workspace = true }
crossterm = "0.28.0"
ratatui = "0.29.0"
lutra-compiler = { workspace = true }
lutra-bin = { workspace = true }
lutra-interpreter = { workspace = true }
