[package]
name = "project2"
resolver = "2"
edition = "2021"

[dependencies]
lutra-bin = { workspace = true }
lutra-runner-postgres = { workspace = true }
postgres = "0.19.10"

[build-dependencies]
lutra-codegen = { workspace = true }
