[package]
name = "project2"
resolver = "2"
edition = "2021"

[dependencies]
lutra-bin = { path = "../../lutra-bin" }
lutra-runner-postgres = { path = "../../lutra-runner-postgres" }
postgres = "0.19.10"

[build-dependencies]
lutra-codegen = { path = "../../lutra-codegen" }
