[package]
name = "lutra-arrow"
publish = ["codeberg-org"]
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
arrow = {workspace = true}
parquet = {workspace = true}
thiserror = {workspace = true}
lutra-bin = {workspace = true}