[package]
name = "lutra-bin"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
lutra-parser = { path = "../lutra-parser" }
tabular = "0.2.0"
thiserror = {workspace = true}
